### ISSUE TITLE
[Question] Memory order

### ISSUE THREAD

**Issue by 0shimax** [01org/mkl-dnn#116]
It seems that we can choose various order of memory. How much performance is decrease if order is fixed to NCHW? Is it recommended to call Reorder?

**Comment by vpirogov** [comment]
Using right memory format is essential to get optimal performance from convolutions. Intel MKL-DNN usage model assumes that convolution and inner product can choose the memory format for data, weights and bias. The rest of primitives are optimized for memory formats that convolution uses, so these are just passed through. If you will create convolution with NCHW format, for instance, it will generally run up to several times slower, as it will have to use GEMM-based implementation instead of JIT direct convolution implementation.

**Comment by 0shimax** [comment]
@vpirogov 
Thank you for your kind reply!
