### ISSUE TITLE
Building Tensorflow with MKLDNN fails 

### ISSUE THREAD

**Issue by nhasabni** [01org/mkl-dnn#121]
MKLDNN needs -fexceptions, but Tensorflow disables exceptions using -fno-exceptions.

Having a version of MKLDNN without using exceptions would solve the problem.

**Comment by vpirogov** [comment]
Intel MKL-DNN by design relies on the exceptions both internally and in C++ API to handle errors. So there's no way to build the library without exceptions. For applications that cannot use exceptions (or any other C++ 11 features) Intel MKL-DNN provides [C API](https://github.com/01org/mkl-dnn/blob/master/include/mkldnn.h).
