### ISSUE TITLE
Can MKL-DNN reduce lib size to optimize deployment?

### ISSUE THREAD

**Issue by a3213105** [01org/mkl-dnn#144]
just like what libtensorflow does

https://github.com/tensorflow/tensorflow/blob/89cf07de7cf864783f262215d724167e24caa68e/tensorflow/python/tools/print_selective_registration_header.py

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms#optimizing-for-deployment

**Comment by emfomenk** [comment]
Hi @a3213105,

Alas MKL-DNN doesn't have such a capability. On the other hand most of the code is JITted at the runtime, so I don't think one can gain a lot from cutting off unnecessary primitives/features.

For the TF it makes more sense, since it has a lot of features, and most of them might no be used at the deployment.

**Comment by a3213105** [comment]
thanks @emfomenk .
but we want to use TF + MKL-DNN on an embedded system, the size of binary is importance to us

**Comment by rsdubtso** [comment]
@a3213105, would a static library work for you in this case?

**Comment by emfomenk** [comment]
Closed as outdated.
Please fill free to re-open if necessary.
