### ISSUE TITLE
Ask to support clip operation

### ISSUE THREAD

**Issue by heagoo** [01org/mkl-dnn#147]
### Description
Clip operation is not supported. In fact, clip is widely used in some cases, for example, to clip the value to [-5, 5].

### Actual behavior
I see many eltwise ops are already supported, but without clip.

### Expected behavior
To support clip operation.

**Comment by emfomenk** [comment]
Hi @heagoo,

Alas, no plan to support clip primitive for now...

To some extend you can use bounded relu (as long as the lowest bound is 0).
On the other hand this eltwise doesn't really depend on the actual layout (as well as any other eltwise primitives just by design). So as a quick workaround you may just take the data a clipped with a single loop (preserving the initial layout).
// *Sorry for this obvious suggestion*

**Comment by heagoo** [comment]
Yes, I get it implemented by myself. Thanks!
