### ISSUE TITLE
does mkldnn support depthwise convolution?

### ISSUE THREAD

**Issue by kriszhangyf** [01org/mkl-dnn#158]
does it support depthwise convolution?
If it supports, there is any  example?

**Comment by emfomenk** [comment]
Hi @kriszhangyf,

Formally speaking MKL-DNN supports groups, which covers the functionality of depthwise convolution:
```
dst[n][c][oh][ow] <-- src[n, c, ih, iw] (*) wei[c][1][1][kh][kw]
```

Here wei is 5D tensor of weights with `number of groups = c`, `oc = 1`, `ic = 1`, and `kh x kw` spatial.

**Comment by kriszhangyf** [comment]
Does it means that the out channel is still c?
can it supports the depthwide conv as
src[n, c, ih, iw] * wei[oc, 1, kh, hw] -> dst[n, oc, oh, ow]?
which oc = g*c

**Comment by emfomenk** [comment]
Convolution has strict definition, so
```
src[n, ic, ih, iw] (*) wei[oc, 1, kh, hw]
```
is illegal, since `ic` in source doesn't match `ic` in weights.

**Comment by jimeiyang** [comment]
Hi @emfomenk, 

Are there any updates on the optimized depthwise convolution?

Thanks

**Comment by emfomenk** [comment]
Hi,

we recently tuned gemm-based implementation for depwise convolution (see 967d7bf). Also we will promote avx2 specialized version for forward pass (maybe in few days).

If you want to check performance for mobile convolutions, you may use benchdnn with mobile-net input file: 3768fb22.

**Comment by emfomenk** [comment]
Just a quick update: optimized avx2 version is here 3edac962.

**Comment by jimeiyang** [comment]
That's awesome! Thanks! I'm still struggling with compiling intel-caffe on macOS. Hope I can test it soon.

**Comment by emfomenk** [comment]
Hi @fei1107,

Depthwise convolution uses regular grouped API (basically `ic = oc = g`, so I think IntelCaffe already supports it (since IntelCaffe supports grouped convolutions).

**Comment by fei1107** [comment]
Thanks! Do you mean that when ic = oc = g, Intel caffe will automatically run on the optimized depthwise convolution code rather than general convolution?

**Comment by fei1107** [comment]
Many thanks! Does the depthwise conv support quantization for int8 on avx512 right now? And one last question, how can I fuse the convolution and relu layer in intel caffe, do I have to set some flag, or it can fuse automatically?Really appreciate for your answer!

**Comment by emfomenk** [comment]
> Does the depthwise conv support quantization for int8 on avx512 right now? 

Not sure I understand the question.

- If you are asking whether MKL-DNN supports int8 depthwise convolution then the answer is **yes**, thought we don't have a kernel with direct implementation (so int8-gemm-based fallback will be used).

- If you are asking whether you can quantize the input/weights (`f32 -> int8`) or dequantize output (`int8 -> f32`) then the answer is also **yes**. You can do that via reorders.

- Also you can apply `output_scaling` factor for int8 depthwise convolution output.

Long story short, everything applicable for regular convolution is applicable for depthwise convolution as well (since in MKL-DNN depthwise convolution is treated as the regular one).


> how can I fuse the convolution and relu layer in intel caffe, do I have to set some flag, or it can fuse automatically?

AFAIK, IntelCaffe will do some fusion on the fly. In particular it can merge convlutions followed by relu. It also can fuse convolutions followed by batch-normalization (on inference), and residual blocks (conv + relu + sum). For more details see: [compile rules in net.cpp](https://github.com/intel/caffe/blob/master/src/caffe/net.cpp). You can also try running your topology and look at the output of IntelCaffe. If you run ResNet-50 you most likely will see something like:
```
...
I0305 23:44:59.466156  3880 remove_batch_norm.cpp:276] Dropped Layer: bn_conv1 # <-- batch normalization is fused
...
I0305 23:44:59.466895  3880 net.cpp:739] Dropped layer: res2a_branch2a_relu # <-- relu is fused
...
```

**Comment by fei1107** [comment]
@emfomenk That's so great! I will try that after my network's training is done. Once again , thanks for your reply!

**Comment by kwiersch** [comment]
Hi @sfraczek, `oc` a multiple of `ic = g` is a valid convolution. In this case, within each group there are two output filters for each input filter. But note that unlike the case of depthwise convolutions (`g = ic = oc`), there is currently no jitted implementation, so convolutions such as `mb1_g32ic32oc64_ih10oh10kh3ph1` will dispatch to gemm-based implementation.
