### ISSUE TITLE
Any plans to support quantized kernels for SSE4.2?

### ISSUE THREAD

**Issue by xyzsam** [01org/mkl-dnn#168]
Hi,

It seems that all of the support for quantized kernels is limited to CPUs with AVX support. Is there any plan to add support quantized kernels on SSE4.2? I understand that AVX has better support for low precision integer math, but SSE4.2 does have some 16-bit integer math instructions too.

Also, it looks like for SSE4.2, there is no vectorized pooling kernel - is that correct?

**Comment by emfomenk** [comment]
Hi @xyzsam,

Yeah, you are right, we don't have lower-precision primitives optimized for <AVX512.
So far no plans for that...

We have sse4.2 optimized pooling (see [this](https://github.com/01org/mkl-dnn/blob/master/src/cpu/cpu_engine.cpp#L149)). But it supports f32 only.

**Comment by xyzsam** [comment]
Thanks for the clarification. For the pooling, I'm having trouble getting MKL-DNN to use the optimized pooling. What data format does the input need to be in for that? I'm using nchw and I'm seeing my implementation use `nchw_pooling_fwd_t`.

**Comment by emfomenk** [comment]
Oh, I should've mentioned that. The jitted version works with `nChw8c` format.
This format is what our jitted convolutions require (the format is vectorization-friendly).
See [example step 10](http://01org.github.io/mkl-dnn/) in MKL-DNN documentation.
It explains that for performance reasons you want keeping the data in format convolutions ask you.
Otherwise the performance might be far from excellent and in that case nchw_pooling_fwd_t would also work fine :)

**Comment by xyzsam** [comment]
Okay, great, thanks. Keeping the data format the way convolutions ask is the next thing I was going to implement :)
