### ISSUE TITLE
Differences with MKL 2017 DNN

### ISSUE THREAD

**Issue by Maratyszcza** [01org/mkl-dnn#34]
What are the differences between this version, and DNN primitives in MKL 2017? I see that the interfaces are different.

**Comment by emfomenk** [comment]
Hi @Maratyszcza,

For the description of current differences please see [this comment](https://github.com/01org/mkl-dnn/issues/10#issuecomment-283418614).

MKL-DNN interface was re-thought, in particular layout (`mkldnn_memory_desc_t`) become transparent, while in Intel MKL it is opaque for user. For the rest Intel MKL (DNN primitives) and MKL-DNN are pretty close.

**Comment by Maratyszcza** [comment]
Thank you. Will Intel MKL adapt interfaces of MKL-DNN in the future, or there will be two parallel sets of interfaces?

**Comment by emfomenk** [comment]
We definitely want to use one single API for both Intel MKL and MKL-DNN. This single API will be MKL-DNN one.
Alas, right now I can't estimate when this will happen. Also since Intel MKL has to provide backward compatibility, DNN interface of Intel MKL will also remain supported for time being (at least for several years after deprecation notice).

**Comment by bhack** [comment]
@Maratyszcza Do you plan to integrate in NNPACK?

**Comment by Maratyszcza** [comment]
@bhack Integrate what?

**Comment by bhack** [comment]
I mean using NNPACK internal implementation and MKL-DNN with the same NNPACK API..

**Comment by Maratyszcza** [comment]
No, this wouldn't be efficient. MKL-DNN uses a different layout for layers.

**Comment by bhack** [comment]
@Maratyszcza So.. We need to interface another engine in tiny 😉
