### ISSUE TITLE
Can Inputs and outputs memory buffer be changed without creating a new primitive?

### ISSUE THREAD

**Issue by 4pao** [01org/mkl-dnn#38]
1.       Do any jitted code hard code the destination or source address of memory primitive? Or it can decide where to input and output during runtime.
2.       Do all the convolution kernels jitted share same code cache? If two or more convolutions have the same configuration, do they share the same jitted code?

**Comment by emfomenk** [comment]
Hi @4pao,

1. Jitted code itself doesn't hard code the source and destination addresses. The API allows you to substitute new source/destination pointers in `mkldnn::memory`, using `mkldnn_memory_set_data_handle()` function.

2. The kernel is shared with the convolution (e.g. by different threads). Though if you create two absolutely identical convolutions, jitted code would be generated twice. But this is not a big burden since generated code is typically no more than 8 KB (most likely even smaller).
