### ISSUE TITLE
padR in Convolution primitive

### ISSUE THREAD

**Issue by uu-praveeng** [01org/mkl-dnn#49]
Hi ,

During the creation of convolution primitive descriptor(convolution_forward::desc)
why do we need the padR which is passed as input arguement.
std::vector<int> padR = { cd.padh, cd.padw };
        for (int i = 0; i < 2; ++i) {
        if ((cd.ih + cd.padh + padR[0] - cd.kh)/cd.strh + 1 != cd.oh) ++padR[0];
        if ((cd.iw + cd.padw + padR[1] - cd.kw)/cd.strw + 1 != cd.ow) ++padR[1];
        }

Since padding information is already passed before the above input argument in the argument list.

Thanks,
G. Praveen.

**Comment by emfomenk** [comment]
Hi @uu-praveeng,

In order to specify convolution entirely one should set top, left, bottom, and right paddings.
For that MKL-DNN has `padding_l[]` and `padding_r[]` parameters in `mkldnn_convolution_forward_desc_init()`.
Here for 2D case: `padding_l[] = { padding_top, padding_left }`, `padding_r = { padding_bottom, padding_right }`.

In most cases `padding_l[:] == padding_r[:]`. But sometimes one may want to have them different. Unfortunately once we implemented our unit-tests we put only padding_l as input parameters.
Hence to get the right `padding_r` (having input shape, output shape, conv kernel size, conv strides and left and top paddings) we have to apply this strange magic :) In a nutshell test just tries to find minimal padding_bottom (`padR[0]`) and padding_right (`padR[1]`) so that computed output shape would be the same as we have specified in the test input arguments.

> output_height = (input_height + padding_top + padding_bottom - kernel_height) / conv_stride_h + 1
> output_width = (input_width + padding_left + padding_right - kernel_width) / conv_stride_w + 1
