### ISSUE TITLE
What is the "Real Code" of the convolution computation?

### ISSUE THREAD

**Issue by sjlee7748** [01org/mkl-dnn#56]
Hi, I want to know actual code that performs the convolution operation 
and there are a few facts I found out when I analyzed the code.

1. Convolution computation uses the JIT assembler, "xbyak"
https://github.com/herumi/xbyak/issues/36
2. At AVX512, The line 104 (kernel_->jit_ker(&par_conv);) in the below link is a function that perfoms the convolution operation 
https://github.com/01org/mkl-dnn/blob/master/src/cpu/jit_avx512_mic_convolution.cpp#L104

But, When trying to analyze the inside of a "jit_ker" function through GDB, I cound not trace inside the function and I guess the following code is the convolution code.
https://github.com/01org/mkl-dnn/blob/master/src/cpu/jit_avx512_mic_conv_kernel_f32.cpp

Can you tell which part is the code that computes the real convolution?

Also I add a question.
It seems that the part that made JIT code for Convolution is [here,](https://github.com/01org/mkl-dnn/blob/master/src/cpu/jit_avx512_mic_conv_kernel_f32.cpp) I wonder about the address pattern.

Is there a way to pick addresses from the JIT assembly?

Thank you for reading my question!

**Comment by sjlee7748** [comment]
Also I add a question.
It seems that the part that made JIT code for Convolution is [link](https://github.com/01org/mkl-dnn/blob/master/src/cpu/jit_avx512_mic_conv_kernel_f32.cpp), I wonder about the address pattern here.

Is there a way to pick addresses from the JIT assembly?

**Comment by rsdubtso** [comment]
Convolution compute kernel(s) exist only at runtime. If you want to examine the assembly, you'd need to write the generated code to a file. Unfortunately currently mkl-dnn does not make it easy, and you will have to do that yourself. It can be done it using Xbyak's `dump()`, but I think writing to a binary file makes more sense. For that you'd need to write `getSize()` bytes of data pointer to which is by `getCode()`. After that you can use `objdump` to examine the disassembly like this: `objdump -D -b binary -mi386:x86-64 dump.bin > dump.s`.

It's very tedious, but you can also step through JIT code instruction-by-instruction from GDB or you can use the `x` command to examine the code. For example: `x /20i $pc` would dump next 20 instructions, so you can use it to generated code once you set the breakpoint correctly and stepped to a right instruction.

You can also add `db(0xcc)` (`int 3` instruction) to the code generation function you want to inspect so that GDB automatically breaks in the resulting code.
