### ISSUE TITLE
do we have backward FC without bias?

### ISSUE THREAD

**Issue by tensor-tang** [01org/mkl-dnn#58]
hi,

I did not see any example code that test inner product backward without bias, only have samples how to forward without bias, so how about backward? 

Have not implemented or have not given the example? And how to deal with backward without bias?

Thanks very much.

**Comment by emfomenk** [comment]
Hi @tensor-tang,

From mkl-dnn perspective bias is yet another weight (with index 1).
So you need to look at backward wrt weights in order to find out how compute inner-product backward [with](https://github.com/01org/mkl-dnn/blob/master/tests/gtests/test_inner_product_backward_weights.cpp#L218) or [without](https://github.com/01org/mkl-dnn/blob/master/tests/gtests/test_inner_product_backward_weights.cpp#L194) bias. Note `mkldnn_undef` in the latter example: that means omitting backward computations wrt bias.

Alternative way is to pass `NULL` for `diff_bias_desc` in `inner_product_backward_weights(...)` [initialization function](https://github.com/01org/mkl-dnn/blob/master/include/mkldnn.h#L598).

**Comment by tensor-tang** [comment]
Thanks @emfomenk 

My fault, I checked out the version that has no examples of without bias. Everything was fine after update code.

Anyway, thanks for your answer.

**Comment by tensor-tang** [comment]
Solved
