### ISSUE TITLE
strides type

### ISSUE THREAD

**Issue by kruus** [01org/mkl-dnn#63]
Even though the fortran APIs may support negative strides, 
the C/C++ code would be incorrect with negative stride values.
Choices:
- support -ve stride "everywhere" [hard]
- assert strides are positive
- make strides a non-negative type
Now, I realize there is no unsigned ptrdiff_t, but maybe size_t
(with a static_assert that sizeof(size_t)>=sizeof(ptrdiff_t))
would be a better choice?

There are a few other cases where int loop indices should be size_t, I think.
(from compiler warnings on a [non-JIT] 32-bit int HPC system). I can point these
out if interested.

**Comment by rsdubtso** [comment]
Sorry for keeping this without a reply. This is a embarrassing question because we are only targeting x86_64 and have a large leeway in how we can (incorrectly) mix signed/unsigned integers of different sizes and still get correct results in most of the cases.

I think that it is useful to use signed types for tensor dimensions (makes padding computations much easier), but maybe not for the strides. However this leads to the need to be even more careful when mixing signed and unsigned integers. We found that Microsoft compiler is actually quite paranoid regarding this, so maybe part of the fixes will come with the Windows support.

Re: 32-bit int HPC system: does it have 32-bit ptrdiff_t? In other words, do you have troubles with being unable to address >2G elements using this approach?

**Comment by kruus** [comment]
My HPC compiler has options -size_t32 [default] and -size_t64
I find ptrdiff_t, intptr_t and void* are 8 bytes long _with both options_.

Glad I verified -- I definitely don't want to support 4-byte size_t with 8-byte ptrdiff_t option.

---
From the sxc++ manuals, it seems -size_t32 is a historical relic that began as an
O/S-related -over2g option, and later morphed (when size_t became unsigned?) to the
current -size_t32/64 options with cut-off at 4G array sizes.

Old docs for -over2g:
> The size over 2GB cannot be defined for arrays, structures, unions, and classes before SUPER-UX R11.1

Docs for -size_t32: 
> When the type of size_t is unsigned int (default), the use of arrays, structures, unions, and classes of 4 GB or more is unavailable

**Comment by rsdubtso** [comment]
Thanks for the info. Since use of signed type here was a conscious decision here, I'm closing this. We will add asserts / do proper error checking.
