### ISSUE TITLE
How to use the date type of s16s16s32 and u8s8u8 for inference?

### ISSUE THREAD

**Issue by heagoo** [01org/mkl-dnn#67]
I see there are s16s16s32 and u8s8u8 support in readme. Is there any examples for how to use it? And further more, have you compared the performance with fp32 (on Skylake E5 servers)?
If there is no example, where should I look into to find out how to use it? Thanks!

**Comment by rsdubtso** [comment]
The u8s8u8 requires a CPU that support AVX512VL feature, and s16s16s32 requites a CPU that supports AVX512_4VNNIW feature. Unfortunately this means that both won't run on Skylake E5 since it only supports AVX2.

**Comment by kanshuzhi** [comment]
Hello, @rsdubtso @heagoo 

I have one machine with AVX512VL support. Is there any tutorial or example how to use this kernel?

Best Regards

**Comment by emfomenk** [comment]
Hi @kanshuzhi,

Sorry for delay.
I've just pushed new benchmark [**benchdnn**](https://github.com/01org/mkl-dnn/tree/master/tests/benchdnn). It covers u8s8u8 as well as s16s16s32 and others. You may want to take a look there.  So far that the only code that uses u8s8u8 convolution...

Alas, we don't have a *real world* application that shows applicability of such convolution... since int8 convolution is ~1.5x faster than f32 analogue on Skylake Server we really would like to find such an application to demonstrate the benefit.
