### ISSUE TITLE
AVX512

### ISSUE THREAD

**Issue by vkirangoud** [01org/mkl-dnn#7]
Hi, Does this library is optimized using AVX-512 intrinsic?

**Comment by vpirogov** [comment]
Hi,

AVX-512 optimizations are not yet available in the library. We are working on the implementation. For low level optimizations we don't use intrinsics, as these are not portable between compilers. We use JIT engine called XByak. 

Vadim

**Comment by rsdubtso** [comment]
I'm reopening this till we have optimized AVX512 code path. #

**Comment by aminems** [comment]
@vpirogov do you think that using XByak is giving better performance than intrinsics ?
Thanks,
Mohamed

**Comment by rsdubtso** [comment]
Xbyak (or any other run-time code generation technique) allows producing code that matches a computation exactly. For convolutions the most important part is that this allows exact unrolling of the innermost loops which are typically short.

Another issue with compiler-generated code is general-purpose register allocation. Compilers typically produce more fills/spills than necessary, and also not always able to generate optimal address computations because offsets are not known at compile time and have to be kept in registers / stack / memory. Such computations often result in imul/idiv instructions that are expensive. With run-time code generation, offsets are pre-computed and hard-coded thus removing the need for expensive instructions and the pressure on GPRs in compute kernels.

**Comment by vpirogov** [comment]
Another reason why we use XByak is that this is very portable solution. It will work with any C++ compiler while intrinsics are compiler specific.

**Comment by bhack** [comment]
About portabilty there was also and old efffort to have an ARM version at https://github.com/wanabe/xtaak but it is unmaintaned.

**Comment by vpirogov** [comment]
We added initial AVX512 optimizations in the latest update.
