### ISSUE TITLE
Does concat support different input format?

### ISSUE THREAD

**Issue by tensor-tang** [01org/mkl-dnn#70]
On KNL.

I found that in branch inceb4 of googlenet v1, one input format of concat layer is nChw8c, however the others are nChw16c.

My question is that does the concat suppot this case(the input formats are different)?

Since this case are not included in the unit test.

**Comment by emfomenk** [comment]
Hi @tensor-tang,

Concat should support arbitrary formats for input and output because inside (in the worst case when there is no optimized version) reorders are used.

The problem with googlenet_v1 here is that this exact fallback happens. That slowdowns concat (due to not very good parallelization and lack of `nChw8c <-> nChw16c` optimized reorder). We are aware of that issue and are going to address it soon (maybe in a week or so).

Once implemented we will close this issue to notify you.

**Comment by tensor-tang** [comment]
@emfomenk 
Thanks very much.
