### ISSUE TITLE
can't build on Sierra OS X

### ISSUE THREAD

**Issue by geoHeil** [01org/mkl-dnn#84]
HI,
I have problems building on Sierra OS X with GCC7
```
[ 37%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/ref_pooling.cpp.o
[ 38%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/ref_softmax.cpp.o
[ 39%] Linking CXX shared library libmkldnn.dylib
g++-7: error: unrecognized command line option '-z'
g++-7: error: unrecognized command line option '-z'
g++-7: error: unrecognized command line option '-z'
make[2]: *** [src/libmkldnn.0.9.0.dylib] Error 1
make[1]: *** [src/CMakeFiles/mkldnn.dir/all] Error 2
```

**Comment by rsdubtso** [comment]
Please try this gist: https://gist.github.com/rsdubtso/18d25961b15667c4a0bf523933f7acb4

**Comment by rsdubtso** [comment]
Quick update: if building with homebrew llvm, you need to specify additional LDFLAGS:

`CC=$(brew --prefix llvm)/bin/clang CXX=$(brew --prefix llvm)/bin/clang++ LDFLAGS=-L$(brew --prefix llvm)/lib cmake ..`

**Comment by mikowals** [comment]
I tried building with homebrew llvm a couple of days ago.  Ultimately it failed because it could not find `pthread.h`.   

>-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is Clang 4.0.0

...

>-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at /usr/local/Cellar/cmake/3.9.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.9.0/share/cmake/Modules/FindThreads.cmake:212 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  tests/gtests/gtest/CMakeLists.txt:9 (find_package)

I also needed to add `include(CheckCXXCompilerFlag)` in `CMakeLists.txt` to avoid error from not finding `CHECK_CXX_COMPILER_FLAG`.

Building with gcc and g++ was fine and built with all tests passing.  I could see the compiler avoids the `-fopenmp` flag and reports `COMPILER_SUPPORTS_FOPENMP - Failed`.

**Comment by vpirogov** [comment]
Closing this at the request is tracked in #10 already.
