### ISSUE TITLE
How to use mkl-dnn?

### ISSUE THREAD

**Issue by fengyuleidian0615** [01org/mkl-dnn#9]
Didn't dig much deeper into the code, just go through the Readme, 
my question is how to use mkl-dnn? Same as using MKL with caffe by defining BLAS := mkl ?

btw any any benchmark result (mkl-dnn vs original mkl)?

**Comment by emfomenk** [comment]
Hi,

There is an experimental support of mkl-dnn in intel caffe (so far forward pass only).
In order to try it set MKLDNN_ROOT and USE_MKLDNN_AS_DEFAULT_ENGINE in Makefile.config ([see](https://github.com/intel/caffe/blob/master/Makefile.config.example#L50) example). Alternatively you may specify MKLDNN engine in topology prototxt.

We try keeping mkl-dnn and Intel MKL synchronized, but minor differences are possible. In particular Intel MKL doesn't distinguish forward propagation in inference and training modes (so mkl-dnn may outperform Intel MKL for classification tasks).

p.s. mkl-dnn is currently optimized for avx2 only, while Intel MKL has optimized avx2 and avx512 primitives. We are working on extending platform support.

**Comment by fengyuleidian0615** [comment]
Thanks your explanations, very helpful.
