### ISSUE TITLE
Is there any performance issue that I build MKLDNN in Core Machine and run on KNL/BDW/SKX machine ?

### ISSUE THREAD

**Issue by etaf** [01org/mkl-dnn#90]
Hi, 
Is there any performance issue that I build MKLDNN in Core Machine and run on KNL/BDW/SKX machine ?
If not,  It maybe an option that also release the built library like mkl.

**Comment by rsdubtso** [comment]
There are parts of MKL-DNN that rely on compiler optimizations (some reorders, particular cases of other primitives). If you are using Intel compiler, it may make sense to build MKL-DNN on the target platform because of the `-xHost` flag. There are no plans at the moment to add CPUID-based dispatching for the compiler-generated code. And currently there are no plans for providing binaries.

**Comment by etaf** [comment]
Thanks @rsdubtso , so there is no performance gap between gcc built MKLDNN on Core and gcc built on KNL ?

**Comment by rsdubtso** [comment]
As far as my limited knowledge of gcc goes, there should be no difference by default. You can check which tuning flags are enabled/enabled on each platform via `gcc -O3 -Q --help=target`.

PS. Performance with gcc may be 10-15% lower than with icc for some topologies.

**Comment by etaf** [comment]
@rsdubtso thanks for you patient explanation.
