### ISSUE TITLE
c_api: When primitive_desc_t objects may be destroyed?

### ISSUE THREAD

**Issue by quant** [01org/mkl-dnn#93]
Hi all,

Could we clarify in documentation when the c_api mkldnn_primitive_desc_destroy() function should  be used? The examples make no use of this function and valgrind shows leaked memory for the primitive_desc objects (pd-objects) created with mkldnn_primitive_desc_create(). 

Of course, one can destroy the pd objects when all the net is built. However, destroying the pd objects right after their latest use has negative side effects. For instance, in the simple_net.c example, destroying relu_pd right after mkldnn_primitive_create(&relu, relu_pd) causes subsequent mkldnn_lrn_forward_desc_init() fail with mkldnn_invalid_arguments error.

I apologize for complaining w/o proposing a patch, but maybe the issue is already known.

Thanks,
Dima

**Comment by emfomenk** [comment]
Hi Dima,

All the opaque objects might be destroyed as soon as they are not used anymore.
For example primitive_descs can be destroyed right after corresponding primitive is created.
I definitely agree the documentation doesn't state that point clear...

> For instance, in the simple_net.c example, destroying relu_pd right after mkldnn_primitive_create(&relu, relu_pd) causes subsequent mkldnn_lrn_forward_desc_init() fail with mkldnn_invalid_arguments error.

That happens because of the [following](https://github.com/01org/mkl-dnn/blob/master/examples/simple_net.c#L261):
```
  const_mkldnn_primitive_desc_t relu_dst_pd = mkldnn_primitive_desc_query_pd(
    relu_pd, mkldnn_query_dst_pd, 0);
  ...
  /* here relu_pd destruction was put as far as i understand (*) */
  ...
  const mkldnn_memory_desc_t *lrn_src_md =
    mkldnn_primitive_desc_query_memory_d(relu_dst_pd);
```

As it is pointed in the [queries documentation](http://01org.github.io/mkl-dnn/group__c__api__types__query.html#ga6eebc661a8a3437b49d9c677f8972fc9) constant references are alive only during the lifetime of the parent object. Hence here `relu_dst_pd` is valid until `relu_pd` is alive.
As far as I understand you call `mkldnn_primitive_desc_destroy(relu_pd)` somewhere here (*).
That most likely caused lrn creation failure.

Anyway, you are absolutely right there is memory leakage in our examples.
I will mark this issue as a bug and we will fix that soon.
Thank you for pointing us!

_// I am really sorry for delay with response._

**Comment by quant** [comment]
Hi Evarist!
Thank you for response. I am sorry for having not provided a reproducer. Here it is. With [this patch](https://gist.github.com/quant/78d9124e49f96549c3456696b87e4986#file-simple_net-c-diff) the sample fails thus:

> [.../simple_net.c:300] error: mkldnn_lrn_forward_desc_init(&lrn_desc, mkldnn_forward, mkldnn_lrn_across_channels, lrn_src_md, local_size, alpha, beta, k) returns 3

Regards
Dima
